---
title: "Modeling photosynthesis in 2D using a porous medium approximation"
author: "Chris Muir"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Modeling photosynthesis in 2D using a porous medium approximation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Notes about usage:

- follow convention of Earles *et al.* (2017) of using lowercase variables for element-wise version, e.g. `r_d` and `j_max`.
- `theta_J` should be 1 rather than default of 0.825 because resolution is near- or subchloroplast (see Earles et al. 2017 Eq 8; Terashina and Saeki 1985; Xiao *et al.* 2016).
- `J_max` is ignored; `j_max` used instead. How do I deal with temperature dependence?

In each element, we need local volumetric:

* $r_{\mathrm{d},i}$: nonphotorespiratory CO$_2$ release
  + depends on mitochrondial volume, which depends on stroma volume
* $r_{\mathrm{p},i}$: photorespiratory CO$_2$ release
  + depends on local CO$_2$ assimilation $r_{\mathrm{c},i}$ and $C_{\mathrm{liq},i}$. These are solved for
  + depends on $\Gamma^*$. This is static property of Rubisco.
  + Equation is $r_{\mathrm{p},i} = \frac{r_{\mathrm{p},i} \Gamma^*}{C_{\mathrm{liq},i}}$
* $r_{\mathrm{c},i}$: local CO$_2$ assimilation rate
  + $r_{\mathrm{c},i} = \text{min}(w_{\mathrm{c},i}, w_{\mathrm{j},i})$ 
  + $w_{\mathrm{c},i}$ and $w_{\mathrm{j},i}$ are local Rubisco-limited carboxylation rate and the RuBP regeneration-limited carboxylation rate, respectively.
  + $w_{\mathrm{c},i}$ depends on local $C_{\mathrm{liq},i}$ (calculated), local Rubisco concentration $()$
  
## Explanation of equations (maybe this will go in help pages, I dunno)

### Nonphotorespiratory CO~2~ release (i.e. dark respiration $R_\mathrm{d}$)

Stroma volume should be calculated from chloroplast concentration and related to light absorption I think

$\mathrm{stroma}_i$ is the volume of stroma in element i



# OLD - switching to approach that is element-wise

$R_\mathrm{d}$ is specified on an area basis ($\mu \text{mol}~\text{m}^{-2}~\text{s}^{-1}$). The total respiration per area can be subdivided into contributions from the palisade and spongy mesophyll layers:
$$R_\mathrm{d} = R_\mathrm{d,palisade} + R_\mathrm{d,spongy}$$
Based on Tholen and Zhu (2011), the corresponding volumetric values denoted with lowercase $r_\mathrm{d}$ are: 

$$r_\mathrm{d,palisade} = \frac{R_\mathrm{d,palisade}}{S_\mathrm{m,palisade} V_\mathrm{m}}$$

$$r_\mathrm{d,spongy} = \frac{R_\mathrm{d,spongy}}{S_\mathrm{m,spongy} V_\mathrm{m}}$$

### Electronic transport rate in the chloroplast stroma ($J$)

$J_\mathrm{max}$ is specified on an area basis ($\mu \text{mol}~\text{m}^{-2}~\text{s}^{-1}$). In the `photo()` model, actual $J$ is a function of irradiance and other parameters (see `photosynthesis:::J`). In this model, we calculate the element-wise volumetric $j_\mathrm{max}$ so that it sums to a $J_\mathrm{max}$ value specified by the user when $\mathrm{PPFD} = \infty$. The total electron transport rate per area can be subdivided into contributions from the palisade and spngy mesophyll layers:

$$J_\mathrm{max} = J_\mathrm{max,palisade} + J_\mathrm{max,spongy}$$
Based on Tholen and Zhu (2011), the corresponding volumetric values denoted with lowercase $j_\mathrm{max}$ are: 

$$j_\mathrm{max,palisade} = \frac{J_\mathrm{max,palisade}}{S_\mathrm{m,palisade} V_\mathrm{s}}$$

$$j_\mathrm{max,spongy} = \frac{J_\mathrm{max,spongy}}{S_\mathrm{m,spongy} V_\mathrm{s}}$$
